language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'

before_install:
  - chmod +x mvnw

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp target/*.jar before-deploy/
  - cd before-deploy && zip -r daengbu.zip before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/daengbu.zip deploy/daengbu.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: daengbu-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until-deployed: true
    on:
      repo: violetbeach/Daengbu
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: daengbu-deploy
    key: daengbu.zip
    bundle_type: zip
    application: daengbu
    deployment_group: daengbu-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: violetbeach/Daengbu
      branch: master
    
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ti6419@gmail.com